### ISSUE TITLE
Workflow does nothing

### ISSUE THREAD

**Issue by ennioVisco** [mooltiverse/nyx-github-action#1]
Hello,

I'm trying to adopt nyx, but I can't succeed.

## Scenario
I have a gradle project, but my goal for the moment is to manually get a changelog and bump the version accordingly, via Github Actions. 
I tried to reproduce the suggested workflow [here](https://github.com/ennioVisco/webmonitor/actions/runs/4915567208/jobs/8778210262), but it does nothing (nor reports any error).

Any idea why I cannot get new releases from it?

**Comment by flelli** [comment]
By the log I see it runs correctly, but you only run Infer, which only reads the repo and creates a new version (but does not apply it).
You need to run the `make` command to get the changelog.

**Comment by ennioVisco** [comment]
> By the log I see it runs correctly, but you only run Infer, which only reads the repo and creates a new version (but does not apply it). You need to run the `make` command to get the changelog.

I was running first `infer` then `publish`, like suggested in [Combined release process](https://github.com/mooltiverse/nyx-github-action#combined-release-process).
I now also added the `make` and `mark` processes, and all the 4 of them are with the same parameters:
```yml
  with:
          changelogPath: 'CHANGELOG.md'
          preset: 'extended'
          resume: 'true'
          releaseLenient: 'true'
          stateFile: '.nyx-state.json'
          summaryFile: '.nyx-summary.txt'
```

And still no release is present, so I think this issue is still relevant.
