### ISSUE TITLE
Properly passing authentication options

### ISSUE THREAD

**Issue by ennioVisco** [mooltiverse/nyx-github-action#2]
I can see a couple of issues:

- The environment variable for the `NYX_VERBOSITY` is overridden internally if no verbosity is specified after `with`
- The authentication fails despite passing:

```yaml
env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NYX_RELEASE_TYPES_PUBLICATION_SERVICES: 'GITHUB'
          NYX_SERVICES_GITHUB_NAME: 'GITHUB'
          NYX_SERVICES_GITHUB_TYPE: 'GITHUB'
          NYX_SERVICES_GITHUB_OPTIONS_AUTHENTICATION_TOKEN: "{{#environmentVariable}}GH_TOKEN{{/environmentVariable}}"
          NYX_SERVICES_GITHUB_OPTIONS_REPOSITORY_NAME: 'name'
          NYX_SERVICES_GITHUB_OPTIONS_REPOSITORY_OWNER: 'user'
```

([Related run](https://github.com/ennioVisco/webmonitor/actions/runs/4930833424/jobs/8812234665))
